#===-- lib/Module/Makefile ---------------------------------*- Makefile -*--===#
#
#                     The KLEE Symbolic Virtual Machine
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
#===------------------------------------------------------------------------===#
#PARALLEL_DIRS = AssertSlice

LEVEL=../..

#PARALLEL_DIRS = Dyck
LIBRARYNAME=kleeModule
DONT_BUILD_RELINKED=1
BUILD_ARCHIVE=1

include $(LEVEL)/Makefile.common
